import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'
// import { getProducts } from '../redux/actions/productActions'
import { Product, Products } from '../lib/types'
import { productActions } from '../redux-store/productsSlice/productsSlice'
import { useAppDispatch } from '../lib/hooks/hooks'
import { fetchInitialProducts } from '../redux-store/productsSlice/productsSlice'

type Props = {
  products?: Products
}


const Home: NextPage = (props: Props) => {

  const cart = useSelector((state: any) => state.cart)
  const products = useSelector((state: any) => state.products)
  const dispatch: any = useAppDispatch()

  console.log("products", products)

  useEffect(() => {
    if (products.status === 'idle') {
      dispatch(fetchInitialProducts())
    }

  }, [products.status, dispatch])

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Ecommerce Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Main Page
        </h2>
        <div>
          <h2>Products</h2>
          <ul>
            {/* 
            {products.data.map((product: Product) => (
              <li key={product.id}>
                <div>
                  <Image src={product.image} alt={product.name} width={200} height={200} />
                </div>
                <div>
                  <h3>{product.name}</h3>
                  <p>{product.description}</p>
                  <p>{product.price}</p>
                  <button onClick={() => dispatch(productActions.addToCart(product))}>Add to cart</button>
                </div>
              </li>
            ))} */}

          </ul>

        </div>
      </main>

    </div>
  )
}




export default Home
